document.writeln("	<footer>");
document.writeln("		<div class=\'footer\'>");
document.writeln("			<div class=\'footera\'>");
document.writeln("				<h2>产品设备</h2>");
document.writeln("				<div><a href=\'product_details.html?commoid=0\'>金牛座</a>");
document.writeln("				<a href=\'product_details.html?commoid=1\'>双子座</a>");
document.writeln("				<a href=\'product_details.html?commoid=2\'>白羊座</a>");
document.writeln("				<a href=\'product_details.html?commoid=3\'>综合机</a></div>");
document.writeln("				<div><a href=\'product_details.html?commoid=6\'>咖啡机</a>");
document.writeln("				<a href=\'product_details.html?commoid=5\'>桌面制冰机</a>");
document.writeln("				<a href=\'product_details.html?commoid=7\'>自动售餐机</a>");
document.writeln("				<a href=\'product_details.html?commoid=4\'>熟食机-饮料机</a></div>");
document.writeln("				<div><a href=\'product_details.html?commoid=8\'>薯条机</a>");
document.writeln("				<a href=\'product_details.html?commoid=9\'>糖果机</a></div>");
document.writeln("			</div>");
document.writeln("			<div class=\'footerc\'>");
document.writeln("				<h2>新闻中心</h2>");
document.writeln("				<a href=\'new_show.html\'>展会</a>");
document.writeln("			</div>");
document.writeln("			<div class=\'footerd\'>");
document.writeln("				<h2>公司讯息</h2>");
document.writeln("				<a href=\'recruitment.html\'>诚聘英才</a>");
document.writeln("				<a href=\'contact.html\'>征求合作</a>");
document.writeln("			</div>");
document.writeln("			<div class=\'footere\'>");
document.writeln("				<a href=\'tel:13335837295\'>133-3583-7295</a>");
document.writeln("				<p>周一至周五 07:50~17:00</p>");
document.writeln("				<div class=\'footere_div\'>");
document.writeln("					<div class=\'footere_div_a\'>");
document.writeln("						<a href=\'sms:133-3583-7295\'></a>");
document.writeln("						<div>");
document.writeln("							<div class=\'footere_div_a_top\'></div>");
document.writeln("							<div class=\'footere_div_a_bottom\'></div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'footere_div_b\'>");
document.writeln("						<a href=\'http://wpa.qq.com/msgrd?v=3&uin=183395456&site=qq&menu=yes\' target=\'_break\'></a>");
document.writeln("					</div>");
document.writeln("					<div class=\'footere_div_c\'>");
document.writeln("						<a href=\'javascript:(0)\'></a>");
document.writeln("					</div>");
document.writeln("					<div style=\'clear: both;\'></div>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<div style=\'clear: both; width: 0px;\'></div>");
document.writeln("		</div>");
document.writeln("	</footer>");