document.writeln("<div class=\'footer_prev\'>");
document.writeln("	<div>");
document.writeln("		<strong class=\'footer_prev_strong\'>您有售货机购买需求？立刻联系我们吧！</strong>");
document.writeln("		<div class=\'footer_prev_div\'>");
document.writeln("			<div class=\'footer_prev_div_left\'>联系我们</div>");
document.writeln("			<div class=\'footer_prev_div_right\'><img data-src=\'image/lxwm.svg\'/></div>");
document.writeln("			<div style=\'clear: both\'></div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<p style=\'clear: both\'></p>");
document.writeln("</div>");
document.writeln("	<footer>");
document.writeln("		<div class=\'footer\'>");
document.writeln("			<div class=\'footera\'>");
document.writeln("				<h2>产品设备</h2>");
document.writeln("				<div><a href=\'product_details.html?commoid=0\'>金牛座</a>");
document.writeln("				<a href=\'product_details.html?commoid=1\'>双子座</a>");
document.writeln("				<a href=\'product_details.html?commoid=2\'>白羊座</a>");
document.writeln("				<a href=\'product_details.html?commoid=3\'>综合机</a></div>");
document.writeln("				<div><a href=\'product_details.html?commoid=6\'>咖啡机</a>");
document.writeln("				<a href=\'product_details.html?commoid=5\'>桌面制冰机</a>");
document.writeln("				<a href=\'product_details.html?commoid=7\'>自动售餐机</a>");
document.writeln("				<a href=\'product_details.html?commoid=4\'>熟食机-饮料机</a></div>");
document.writeln("				<div><a href=\'product_details.html?commoid=8\'>薯条机</a>");
document.writeln("				<a href=\'product_details.html?commoid=9\'>糖果机</a></div>");
document.writeln("				<p style=\'clear: both;\'></p>");
document.writeln("			</div>");
document.writeln("			<div class=\'footerc\'>");
document.writeln("				<h2>新闻中心</h2>");
document.writeln("				<a href=\'new_show.html\'>展会</a>");
document.writeln("			</div>");
document.writeln("			<div class=\'footerd\'>");
document.writeln("				<h2>公司讯息</h2>");
document.writeln("				<a href=\'recruitment.html\'>诚聘英才</a>");
document.writeln("				<a href=\'contact.html\'>征求合作</a>");
document.writeln("			</div>");
document.writeln("			<div class=\'footere\'>");
document.writeln("				<p>周一至周五 07:50~17:00</p>");
document.writeln("				<img src=\'image/ewm.jpg\'/>");
/*document.writeln("				<div class=\'footere_div\'>");
document.writeln("					<div class=\'footere_div_a\'>");
document.writeln("						<a href=\'javascript:void(0);\'></a>");
document.writeln("						<div>");
document.writeln("							<div class=\'footere_div_a_top\'><img src=\'image/ewm.jpg\'/></div>");
document.writeln("							<div class=\'footere_div_a_bottom\'></div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'footere_div_b\'>");
document.writeln("						<a href=\'mqqwpa://im/chat?chat_type=wpa&uin=183395456&version=1&src_type=web&web_src=oicqzone.com\' target=\'_break\'></a>");
document.writeln("					</div>");
document.writeln("					<div class=\'footere_div_c\'>");
document.writeln("						<a href=\'javascript:(0)\'></a>");
document.writeln("					</div>");
document.writeln("					<div style=\'clear: both;\'></div>");
document.writeln("				</div>");*/
document.writeln("			</div>");
document.writeln("			<div style=\'clear: both; width: 0px;\'></div>");
document.writeln("		</div>");
document.writeln("	</footer>");